version: "3.7"

services:               
    
    server:
        container_name: 'incidetnsn_python'
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        environment:
            MONGODB_HOST: 'mongodb'
            MONGODB_DB: 'service_now'
            MONGODB_USERNAME: 'incidentUser'
            MONGODB_PASSWORD: 'redhat'
        volumes:
            - ./models:/app/models:rw
        depends_on: 
            - database
        networks:
            - incidentsn_network      
        stdin_open: true 
        tty: true      
               
volumes:
    mongo-volume:
    appdata:
        
networks:
    incidentsn_network:
        driver: bridge        
